# Generated by Django 2.2.13 on 2020-08-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200806_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pedido Realizado'), ('F', 'Fazendo'), ('E', 'Saiu para entrega')], max_length=1, null=True, verbose_name='Status'),
        ),
    ]
